### ISSUE TITLE
Qual licença: Apache ou MIT?

### ISSUE THREAD

**Issue by luisangelorjr** [woliveiras/guetos#3]
Gostaria de tentar levantar a questão sobre qual licença adicionar nesse modelo de estudos

**Comment by andremaldonado** [comment]
Sei que não faço parte da equipe, mas admiro muito o trampo de vocês e acompanho aqui o GH. Minha dúvida, se é que ela contrubui em algo, é: qual seria a vantagem, nesse caso, de usar a licença da Apache?

**Comment by luisangelorjr** [comment]
Sua dúvida contribui sim, pq ela tbm é a minha rsrs, por isso levantei a discussão
Nunca precisei tratar tanto de licenciamento, mas já aproveitando a deixa, quero entender melhor.

O ponto que levantei foram por esses motivos abaixo herdadas da GPLv3

> O código-fonte obrigatoriamente deve ser público sempre que uma distribuição do software é feita. Ou seja, se você lançar um produto que é uma modificação de um projeto deste tipo, você precisa tornar o seu código público também.

> Modificações do software devem ser lançadas sob a mesma licença.

[link](https://medium.com/trainingcenter/tudo-o-que-voc%C3%AA-precisa-saber-sobre-as-licen%C3%A7as-de-projetos-open-source-aaccbe23e50d)

**Comment by luisangelorjr** [comment]
http://escolhaumalicenca.com.br/
Vou estudar os itens aqui

**Comment by andremaldonado** [comment]
Obrigado por permitir minha participação aqui. Qual é a intenção de licenciar esse trabalho? O que o time do perifacode quer e não quer que outras pessoas façam com essa criação de vocês? Essas perguntas ajudam a entender qual a melhor licença.

**Comment by woliveiras** [comment]
Eu sempre uso MIT em tudo o que envolve compartilhamento de conhecimento, pois não quero saber se alguém está usando meu material, mas que ele sirva para as pessoas. 

MIT dá liberdade total de uso do meu material (desde que a pessoa coloque uma referência do criador do conteúdo), então me serve muito bem.

Quando criei o teach nem pensei nessa parte, mas o objetivo aqui é que as pessoas possam pegar esse repositório e usar como base para montar cursos nas suas regiões, então acredito que uma MIT seja a menos restritiva e que vai servir bem pra gente.

Como a gente não quer patentear nada, não sei se a gente precisa de algo da Apache.

O que acham, jovens?

**Comment by andremaldonado** [comment]
A MIT é a mais simples, parece servir bem. Porém, acredito que ela permita que alguém pegue esse conteúdo, monte um curso e o venda. Se isso for um problema, vocês poderiam usar a Creative Commons não comercial.

Vejam o que faz mais sentido para vocês.

**Comment by geekcom** [comment]
Uma licença Open Source e não comercial seria o ideal, admiro muito o projeto e pretendo implementar um dia na quebrada de onde eu vim.
